### ISSUE TITLE
Not responding to rpc commands

### ISSUE THREAD

**Issue by skinderis** [OmniLayer/omnicore#588]
Hi,
I am trying to run my docker image with **docker-compose up**, but external rpc calls are refused. When I run it with **docker run**, I get results. But when i run **docker-compose up**, I can't get any result from calling rpc method. I try to **curl** with **-vv** flag and it shows:
```
...
* upload completely sent off: 64 out of 64 bytes
< HTTP/1.1 403 Forbidden
< Date: Tue, 10 Apr 2018 20:51:06 GMT
< Content-Length: 0
< Content-Type: text/html; charset=ISO-8859-1
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 172.25.0.1 left intact
```

My .conf file:
```
rpcuser=user
rpcpassword=password
rpcallowip=172.1.2.3/24
rpcport=13544
server=1
port=13543
daemon=0
txindex=1
```
docker-compose.yml file:
```
version: '3'
services:
    tether:
      image: omnicore-docker
      ports:
       - 13543:13543
       - 13544:13544
      volumes:
       - ~/Desktop/omnicore-docker/omnicore_data:/root/omnicore/data/
      command: ./start.sh
      restart: always
```
